name: deploy
run-name: deploy ${{ inputs.distro || 'all' }}

on:
  workflow_dispatch:
    inputs:
      distro:
        description: Distribution to (re)build
        default: all
        type: choice
        options:
          - all
          - ubuntu2604
          - mint22-cinnamon
          - debian13-xfce
          - debian13-server
          - debian13-gnome
          - debian13-kde
          - debian13-proxmox
          - arch
          - cachyos
          - alpine
          - fedora-gnome
          - fedora-kde
          - bazzite
          - bazzite-deck
          - batocera
          - artix-openrc
          - devuan-sway
          - miaos

jobs:
  image:
    permissions:
      contents: write
    uses: ./.github/workflows/build-image.yml
    with:
      distro: ${{ inputs.distro || 'all' }}
